export { buildContext } from './context.js';
export { buildIndex, getIndex, loadIndex, saveIndex, embedIndex } from './indexer.js';
export { resolveProjectPath, findProjectRoot, getCacheDir } from './project.js';
export { countTokens, chunkByTokens, truncateToTokens } from './tokenizer.js';
export { extractChunks } from './extractor.js';
export { initTreeSitter, ensureTreeSitterForExt, treeSitterReady, disposeTreeSitter } from './treesitter.js';
export { scoreChunks, selectChunks } from './retriever.js';
export { getEmbedding, getEmbeddings, getExtractor, cosineSimilarity } from './embeddings.js';
export { analyzeProject, formatHealthReport, formatHealthReportMd } from './analysis.js';
export type { HealthReport, Cycle, UnusedExport, CloneGroup, Hotspot } from './analysis.js';
export { loadProjectConfig, clearConfigCache, globToRegExp, matchesAnyGlob, CONFIG_FILE } from './config.js';
export type { ProjectConfig, ConfigLang } from './config.js';
export { getChangedFiles } from './diff.js';
export type { DiffScope } from './diff.js';
export type * from './types.js';
